pub mod lsp;
pub mod compopts;

pub use lsp::{
    TK_PARAMETER_IDX,
    TK_VARIABLE_IDX,
    TK_FUNCTION_IDX,
    TK_MACRO_IDX,
    TK_KEYWORD_IDX,
    TK_COMMENT_IDX,
    TK_STRING_IDX,
    TK_NUMBER_IDX,
    TK_OPERATOR_IDX,
    TK_DEFINITION_BIT,
    TK_READONLY_BIT,
    TK_DOCUMENTATION_BIT,
    TOKEN_TYPES,
    TOKEN_MODIFIERS,
    LSPServiceProvider
};
